brochure/urls.py
from django.urls import path

from . import views

app_name = 'brochure'

urlpatterns = [
    path('', views.IndexView.as_view(), name='base'),
    path('', views.IndexView.as_view(), name='index'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include #new

urlpatterns = [
    path('', include('icecream.urls', namespace = 'icecream')),
    # path('', include('icecream.urls', namespace='brochure')),
    path('admin/', admin.site.urls),
]

icecream/urls.py
from django.urls import path

from . import views


app_name = 'icecream'

urlpatterns = [
    # create path for add
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:pk>/edit/', views.UpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('add/', views.CreateView.as_view(), name='add'),
    path('<int:pk>/detail/', views.DetailView.as_view(), name='detail'),
    path('<str:selection>/', views.IndexView.as_view(), name ='selection'),

]

##use <int:pk> in urls when allows it to target a specific primary key (pk)

brochure/models.py
from django.db import models

# Create your models here.

icecream/models.py
from django.db import models
from django.urls import reverse

class Icecream(models.Model):
    flavor = models.CharField(max_length = 255)
    base = models.CharField(max_length = 255, choices=[('chocalate', 'chocolate'), ('vanilla', 'vanilla')])
    available = models.CharField(max_length = 255, choices = [('seasonal', 'seasonal'), ('weekly', 'weekly'), ('daily', 'daily')])
    featured = models.BooleanField()
    date_churned = models.DateField()


    def __str__(self):
        return self.flavor

    def get_absolute_url(self):
        return reverse('icecream:index')


# Create your models here.

brochure/views.py
from django.views import generic

class BaseView(generic.TemplateView):
    template_name = '.base.html'
    

class IndexView(generic.TemplateView):
    template_name = 'icecream/index.html'





# Create your views here.

icecream/views.py
from django.views import generic
from django.urls import reverse_lazy ##reverse_lazy returns you after function is completed (use for delete)
from .models import Icecream

class IndexView(generic.ListView):
    template_name = 'icecream/index.html'
    model = Icecream

    def get_queryset(self):
        if 'selection' in self.kwargs:
            filter = self.kwargs['selection']

            if filter == 'featured':
                return Icecream.objects.filter(featured=True)
            else:
                return Icecream.objects.filter(available=self.kwargs['selection'].lower())
        return Icecream.objects.all()

    ##should not have multiple get_queryset methods

    # def get_context_data(self, **kwargs):
    #     daily = Icecream.objects.filter(available = 'daily')
    #     weekly = Icecream.objects.filter(available = 'weekly')
    #     seasonal = Icecream.objects.filter(available = 'seasonal')
    #     featured = Icecream.objects.filter(featured = True)
    #
    #     context = {
    #         'daily': daily,
    #         'weekly': weekly,
    #         'seasonal': seasonal,
    #         'featured': featured
    #     }
    #
    #     return context

class CreateView(generic.CreateView):
    template_name = 'icecream/add.html'
    model = Icecream
    fields = '__all__'

class DeleteView(generic.DeleteView):
    model = Icecream
    success_url = reverse_lazy('icecream:index')

class UpdateView(generic.UpdateView):
    model = Icecream
    fields = '__all__'
    template_name_suffix = '_update_form'

class DetailView(generic.DetailView):
    model = Icecream
    template_name = 'icecream/detail.html'



## Need CreateView, DetailView, DeleteView, UpdateView
## With template_name and model

##create class for CreateView

brochure/templates/brochure/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% load static %}

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>Document</title>
</head>
<body>
  {% include 'brochure/header.html' %}
<main class='main container-fluid'>
  {% block add %}
  {% endblock add %}

  {% block flavors %}
  {% endblock flavors %}
</main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

brochure/templates/brochure/header.html
<nav class='nav container-fluid'>
  <ul class='row'>
    <!-- <li class='col-1'><a href="">About</a></li> -->
    <li class='col-12'><a href="{% url 'icecream:index'%}">Flavors</a></li>
    <li class='col-2'><a href="{% url 'icecream:selection' 'featured' %}">Featured</a></li>
    <li class='col-2'><a href="{% url 'icecream:selection' 'daily' %}">Daily</a></li>
    <li class='col-2'><a href="{% url 'icecream:selection' 'weekly' %}">Weekly</a></li>
    <li class='col-2'><a href="{% url 'icecream:selection' 'seasonal' %}">Seasonal</a></li>
</nav>

icecream/templates/icecream/add.html
{% extends 'brochure/base.html' %}

{% block add %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock add %}

icecream/templates/icecream/create.html
{% extends 'base.html' %}

{% block content %}

  <form method='post'>{% csrf_token %}
    {{form.as_p}}
    <button>Add new</button>
    </form>

  {% endblock content %}

<!-- form method needs csrf_token for protects and form.as_p wraps each field into p tag -->

icecream/templates/icecream/detail.html
<h2>{{ icecream.flavor  }}</h2>
  <ul>
    <li>{{ icecream.base }}</li>
    <li> {{icecream.available}} </li>
    <li> {{icecream.featured}}  </li>
    <li> {{icecream.date_churned}}</li>
  </ul>

icecream/templates/icecream/icecream_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ icecream.id }}"?</p>
    <input type="submit" value="Confirm">
</form>

icecream/templates/icecream/icecream_update_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

icecream/templates/icecream/index.html
{% extends 'brochure/base.html' %}



{% block flavors %}
  <h6 class='btn btn-primary'><a href="{% url 'icecream:add' %}">Add Flavor</a></h6>

{% for icecream in object_list %}
<div class='row'>
<div class="col-12 main-modal">
  <div class="modal-header card">
      <h4>{{ icecream.flavor }}</h4>
    <div class="modal-body d-flex justify-content-around">
      <p><a href="{% url 'icecream:detail' icecream.id %}">Details</a></p>
      <p><a href="{% url 'icecream:delete' icecream.id %}">Delete</a></p>
      <p><a href="{% url 'icecream:edit' icecream.id %}">Edit</a></p>
    </div>
  </div>
</div>
</div>

{% endfor %}
  <!-- <h1>Featured Ice Cream</h1>
{% for icecream in featured %}

  <h3><a href="">{{ icecream.flavor }}</a></h3>
{% endfor %}


<h1>Weekly Flavors</h1>
{% for icecream in weekly %}

  <h3><a href="">{{ icecream.flavor }}</a></h3>
{% endfor %}


  <h1>Daily Flavors</h1>
{% for icecream in daily %}

  <h3><a href="">{{ icecream.flavor }}</a></h3>
{% endfor %}


  <h1>Weekly Flavors</h1>
{% for icecream in weekly %}

  <h3><a href="">{{ icecream.flavor }}</a></h3>
{% endfor %} -->
{% endblock flavors %}